language: ruby
cache: bundler
rvm:
- 2.5.1
before_script:
- bin/rails db:create
- bin/rails db:migrate
script:
- bundle exec rspec spec
deploy:
  provider: heroku
  api_key: 5fe3e605-4b5a-4bbe-99da-d53836efc5e5
  app: still-ridge-80531
