language: ruby
cache: bundler
rvm:
- 2.5.1
script:
- bin/rails db:create
- bin/rails db:migrate
- bundle exec rspec spec
deploy:
  provider: heroku
  api_key:
    secure: g4Hen4ejsNuabFuh1yVU+APRiE9nFDBn0pY8F2izfIzW9Sl/7+MEPcqEz8boYdvGEFd/bmFPiJZhmPcg3R45XcYLVcNSP2wf2zUCzuXpU2fydmzWVPhMuojDIWwqfpJ8MIcD5CXqpMqwGr9ZZE0y22pPhGFi22lwwTYmtdbf9SNclKP1f/3bG2UiL8Kd0WwbQ9PxL4Cifiy6kZmIgYf9iwlegW8e6PPVUfzTAHhFnXsyonDxvQ/crgaioF7lUa7vxfhM0c9/zWLC1wewbbxWhE40lO5rt9ilmGeKAwcQEikATHF3eEQiaKokEL2FQpBY6F/2QV4684Ae/icbBPt2gXtaqKYM32MKEHwmIKwnbNYFBWtVUslDPL7qiIVLz2Rt/Ze0KUN11qpUYI+G4nB6FINZI2Te5rwGqXUXtQFny7iX0PZqR5iIwbNUT/poYVR0odcx7cJiL2h0UNCz2Roxm6ab6kjTFFJyr2gmLImI5ooCYUN0DE6weL/2kZyH5Ahgim2agxbjOlpb7WguTM15cOnJzWtxiYKCpDyAr9aqQDsrg/sZJqf0v8IpjTYiSi2hnF/ad6AvktFeyV/J/MnO8akLXCTFuGeRNtVD4oiGClwrP+KJBpzwflW4y6sTsNp24E4XpTlCfiwlVNUJy6Vbpcwd7YBQ4Om0o8tvTTMa4VU=
  app: acebook
