language: ruby
cache: bundler
rvm:
- 2.5.1
script:
- bin/rails db:create
- bin/rails db:migrate
- bundle exec rspec spec
deploy:
  provider: heroku
  api_key: 6eba380e-4b5d-4586-8426-1e5b0d08d936
  app: acebook
