language: ruby
cache: bundler
rvm:
- 2.5.1
script:
- bin/rails db:create
- bin/rails db:migrate
- bundle exec rspec spec
deploy:
  provider: heroku
  api_key:
    secure: SfB16jKkBZRuWr8QCMb99m0QS8noMhIEO1uJ54YDwTGOmV44MXUOCnXqLo98su5H0CavVpLrxYZKmYGaw2mO+kvKDsBdMXNDOHv+sZ77vK7U3vhv8j9d/B3G4ooClIRUx8fVnB9vN99OqwirybXHcmwHlBRb+rZlwyA1DoabCRcyDe29WLZAtXwLRZ5HvpDZMKGNnoAIPS1wHCMjSgACSymipu8obL6n4YsAA+eFLilenZ4Dk+fkH4Ijs0aqjzB3airNZsNrd2H7FPysTmY/maCwOOWlZshSg3XodE7pE9kpHhi6kA/yUyTAm7d6c9l9DOLWN9kr5jfigR6oAHWTnD3QbRXyXeci1/7YZVn65D6GKfg/7IBJHF64q4/dp0+h+pMU5Gf4DnMJ/oRsQtZ3pto5vCNICxgcC+vF0N/s2SQ148NnKIhuFeGh5gQ8hcoIP0H8sb0Jt1MHhxar3VZYXAiWavwuK4MCb/Dr1vP5qWLTOO9kd0ZeJYSP2VUk7Le6MQY77tMcXzZyQAlPv5voP6LYBqxe26Wv3/VupoLcyLPlahXUrXIJjuWK5pFK9xDUzZ7AUkgN5rTtLXjyH5jNXkZcq6mQBiA6g2EdSyBEsmWbCOD/B9Cw/TD5Uga7Jrfj+0wU0rCcVQAxcBck1lysScUEOPSLaw54Fht2pQty7R4=
  app: acebook
